/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppJournalRouteImport } from './routes/_app/journal'
import { Route as AppExperimentsRouteImport } from './routes/_app/experiments'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppBoxesBoxIdRouteImport } from './routes/_app/boxes/$boxId'
import { Route as AppBoxesBoxIdExperimentsRouteImport } from './routes/_app/boxes/$boxId.experiments'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppExperimentsRoute = AppExperimentsRouteImport.update({
  id: '/experiments',
  path: '/experiments',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBoxesBoxIdRoute = AppBoxesBoxIdRouteImport.update({
  id: '/boxes/$boxId',
  path: '/boxes/$boxId',
  getParentRoute: () => AppRoute,
} as any)
const AppBoxesBoxIdExperimentsRoute =
  AppBoxesBoxIdExperimentsRouteImport.update({
    id: '/experiments',
    path: '/experiments',
    getParentRoute: () => AppBoxesBoxIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/experiments': typeof AppExperimentsRoute
  '/journal': typeof AppJournalRoute
  '/settings': typeof AppSettingsRoute
  '/today': typeof AppTodayRoute
  '/boxes/$boxId': typeof AppBoxesBoxIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/boxes/$boxId/experiments': typeof AppBoxesBoxIdExperimentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/experiments': typeof AppExperimentsRoute
  '/journal': typeof AppJournalRoute
  '/settings': typeof AppSettingsRoute
  '/today': typeof AppTodayRoute
  '/boxes/$boxId': typeof AppBoxesBoxIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/boxes/$boxId/experiments': typeof AppBoxesBoxIdExperimentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/experiments': typeof AppExperimentsRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/today': typeof AppTodayRoute
  '/_app/boxes/$boxId': typeof AppBoxesBoxIdRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/boxes/$boxId/experiments': typeof AppBoxesBoxIdExperimentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/experiments'
    | '/journal'
    | '/settings'
    | '/today'
    | '/boxes/$boxId'
    | '/api/auth/$'
    | '/boxes/$boxId/experiments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/experiments'
    | '/journal'
    | '/settings'
    | '/today'
    | '/boxes/$boxId'
    | '/api/auth/$'
    | '/boxes/$boxId/experiments'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/experiments'
    | '/_app/journal'
    | '/_app/settings'
    | '/_app/today'
    | '/_app/boxes/$boxId'
    | '/api/auth/$'
    | '/_app/boxes/$boxId/experiments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/experiments': {
      id: '/_app/experiments'
      path: '/experiments'
      fullPath: '/experiments'
      preLoaderRoute: typeof AppExperimentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/boxes/$boxId': {
      id: '/_app/boxes/$boxId'
      path: '/boxes/$boxId'
      fullPath: '/boxes/$boxId'
      preLoaderRoute: typeof AppBoxesBoxIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/boxes/$boxId/experiments': {
      id: '/_app/boxes/$boxId/experiments'
      path: '/experiments'
      fullPath: '/boxes/$boxId/experiments'
      preLoaderRoute: typeof AppBoxesBoxIdExperimentsRouteImport
      parentRoute: typeof AppBoxesBoxIdRoute
    }
  }
}

interface AppBoxesBoxIdRouteChildren {
  AppBoxesBoxIdExperimentsRoute: typeof AppBoxesBoxIdExperimentsRoute
}

const AppBoxesBoxIdRouteChildren: AppBoxesBoxIdRouteChildren = {
  AppBoxesBoxIdExperimentsRoute: AppBoxesBoxIdExperimentsRoute,
}

const AppBoxesBoxIdRouteWithChildren = AppBoxesBoxIdRoute._addFileChildren(
  AppBoxesBoxIdRouteChildren,
)

interface AppRouteChildren {
  AppExperimentsRoute: typeof AppExperimentsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTodayRoute: typeof AppTodayRoute
  AppBoxesBoxIdRoute: typeof AppBoxesBoxIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppExperimentsRoute: AppExperimentsRoute,
  AppJournalRoute: AppJournalRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTodayRoute: AppTodayRoute,
  AppBoxesBoxIdRoute: AppBoxesBoxIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
